language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
env:
  global:
    - BABEL_ENV=test
  matrix:
    - PKG_CMD="npm"
node_js:
  - '8'
matrix:
  fast_finish: true
before_install:
  - npm install -g npm@5
  - nvm use $TRAVIS_NODE_VERSION
  - npm set loglevel error
  - npm set progress false
  - 'if [ $PKG_CMD = "yarn" ]; then curl -o- -L https://yarnpkg.com/install.sh | bash && PATH=$HOME/.yarn/bin:$PATH ; fi'
install:
  - $PKG_CMD install
script:
  - $PKG_CMD run build
  - $PKG_CMD run test
after_success:
  - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
  - npm run release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
